[package]
name = "trs"
version = "1.0.1"
edition = "2024"

[dependencies]
clap = "4.5"
flate2 = "1.1"
dirs = "6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4"
indicatif = "0.17.7"